sonar.projectKey=Latz_feed-seeker
sonar.organization=latz-1
sonar.host.url=https://sonarcloud.io

# Source files
sonar.sources=feed-seeker.ts,modules
sonar.tests=tests

# Language settings
sonar.typescript.node=node

# Exclusions
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.old.js

# Test exclusions
sonar.test.exclusions=**/tests/**

# Coverage settings
sonar.javascript.lcov.reportPaths=coverage/lcov.info
